# Generated by Django 4.2 on 2023-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=254)),
                ('date_release', models.DateField()),
                ('description', models.TextField()),
                ('price_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_original', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('steam_deck', models.BooleanField()),
            ],
        ),
    ]
