# Generated by Django 4.2 on 2023-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='alt_text',
            field=models.CharField(default='alt text', max_length=254),
        ),
    ]
