# Generated by Django 4.2 on 2023-04-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='image_url',
            new_name='url',
        ),
    ]
