# Generated by Django 4.2 on 2023-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_url_games_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='brand',
            field=models.CharField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='games',
            name='game_platform',
            field=models.CharField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='games',
            name='operating_systems',
            field=models.CharField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='games',
            name='product_type',
            field=models.CharField(default='N/A', max_length=254),
        ),
    ]
